-- Supabase migration for the existing SQLite catalog.
-- Run this file in Supabase SQL Editor before deploying the application.

create extension if not exists pgcrypto;

-- This migration intentionally starts from a clean schema.
-- It removes only the application tables created below.
drop table if exists public.account_coupons cascade;
drop table if exists public.account_carts cascade;
drop table if exists public.orders cascade;
drop table if exists public.admin_invites cascade;
drop table if exists public.page_views cascade;
drop table if exists public.site_settings cascade;
drop table if exists public.products cascade;
drop table if exists public.discounts cascade;
drop table if exists public.profiles cascade;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  identifier text not null unique,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  "isOwner" boolean not null default false,
  "displayName" text,
  "pictureUrl" text,
  "createdAt" timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin' and "isOwner" = true); $$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;
revoke all on function public.is_owner() from public;
grant execute on function public.is_owner() to anon, authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, identifier, "displayName", "pictureUrl")
  values (
    new.id,
    lower(coalesce(new.email, new.phone, new.id::text)),
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric(12,2) not null,
  "imageUrl" text,
  category text,
  "inStock" boolean not null default true,
  "costPrice" numeric(12,2) default 0,
  "discountPercentage" numeric(5,2) default 0,
  "productImages" jsonb default '[]'::jsonb,
  "stockQuantity" integer default 10,
  featured boolean not null default false,
  "isNew" boolean not null default false
);

create table if not exists public.discounts (
  id bigint generated by default as identity primary key,
  code text unique not null,
  type text not null,
  value numeric(12,2) not null,
  active boolean not null default true
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  items jsonb not null,
  "customerName" text not null,
  province text not null,
  address text not null,
  "nearestLandmark" text not null,
  "phoneNumber" text not null,
  subtotal numeric(12,2) not null,
  "discountCode" text,
  "discountAmount" numeric(12,2) not null,
  "deliveryFee" numeric(12,2) not null,
  "finalTotal" numeric(12,2) not null,
  "accountId" uuid references public.profiles(id) on delete set null,
  "accountOrderNumber" integer,
  status text not null default 'new',
  "isRead" boolean not null default false,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  "storeName" text,
  tagline text,
  "logoUrl" text,
  "heroTitle" text,
  "heroDescription" text,
  "heroImageUrl" text,
  "heroButtonText" text,
  "maintenanceMode" boolean default false,
  "instagramUrl" text,
  "tiktokUrl" text,
  "facebookUrl" text,
  "whatsappUrl" text,
  "aboutTitle" text,
  "aboutText" text
);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('home', 'product')),
  "createdAt" timestamptz not null default now()
);

create table if not exists public.admin_invites (
  identifier text primary key,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.account_carts (
  "accountId" uuid primary key references public.profiles(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.account_coupons (
  "accountId" uuid not null references public.profiles(id) on delete cascade,
  "discountId" bigint not null references public.discounts(id) on delete cascade,
  "savedAt" timestamptz not null default now(),
  primary key ("accountId", "discountId")
);

create index if not exists products_listing_idx on public.products (featured desc, "isNew" desc, id desc);
create index if not exists orders_account_idx on public.orders ("accountId", "createdAt" desc);
create index if not exists orders_created_idx on public.orders ("createdAt" desc);
create index if not exists page_views_type_idx on public.page_views (type);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.discounts enable row level security;
alter table public.orders enable row level security;
alter table public.site_settings enable row level security;
alter table public.page_views enable row level security;
alter table public.admin_invites enable row level security;
alter table public.account_carts enable row level security;
alter table public.account_coupons enable row level security;

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update_own_or_owner on public.profiles;
create policy profiles_update_own_or_owner on public.profiles for update to authenticated
using (id = auth.uid() or public.is_owner()) with check (id = auth.uid() or public.is_owner());

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select to anon, authenticated using (true);

drop policy if exists products_admin_write on public.products;
create policy products_admin_write on public.products for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists discounts_public_active_read on public.discounts;
create policy discounts_public_active_read on public.discounts for select to anon, authenticated
using (active = true);

drop policy if exists discounts_admin_all on public.discounts;
create policy discounts_admin_all on public.discounts for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists orders_select_own_or_admin on public.orders;
create policy orders_select_own_or_admin on public.orders for select to authenticated
using ("accountId" = auth.uid() or public.is_admin());

drop policy if exists orders_insert_own_or_admin on public.orders;
create policy orders_insert_own_or_admin on public.orders for insert to authenticated
with check ("accountId" = auth.uid() or public.is_admin());

drop policy if exists orders_update_admin on public.orders;
create policy orders_update_admin on public.orders for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists orders_delete_admin on public.orders;
create policy orders_delete_admin on public.orders for delete to authenticated
using (public.is_admin());

drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings for select to anon, authenticated using (true);

drop policy if exists site_settings_owner_write on public.site_settings;
create policy site_settings_owner_write on public.site_settings for all to authenticated
using (public.is_owner()) with check (public.is_owner());

drop policy if exists page_views_public_insert on public.page_views;
create policy page_views_public_insert on public.page_views for insert to anon, authenticated with check (true);

drop policy if exists page_views_admin_read on public.page_views;
create policy page_views_admin_read on public.page_views for select to authenticated using (public.is_admin());

drop policy if exists invites_owner_all on public.admin_invites;
create policy invites_owner_all on public.admin_invites for all to authenticated
using (public.is_owner()) with check (public.is_owner());

drop policy if exists carts_own_all on public.account_carts;
create policy carts_own_all on public.account_carts for all to authenticated
using ("accountId" = auth.uid()) with check ("accountId" = auth.uid());

drop policy if exists coupons_own_read on public.account_coupons;
create policy coupons_own_read on public.account_coupons for select to authenticated using ("accountId" = auth.uid());

drop policy if exists coupons_own_insert on public.account_coupons;
create policy coupons_own_insert on public.account_coupons for insert to authenticated with check ("accountId" = auth.uid());

drop policy if exists coupons_own_delete on public.account_coupons;
create policy coupons_own_delete on public.account_coupons for delete to authenticated using ("accountId" = auth.uid());

insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do update set public = true;

drop policy if exists uploads_public_read on storage.objects;
create policy uploads_public_read on storage.objects for select to anon, authenticated
using (bucket_id = 'uploads');

drop policy if exists uploads_admin_insert on storage.objects;
create policy uploads_admin_insert on storage.objects for insert to authenticated
with check (bucket_id = 'uploads' and public.is_admin());

drop policy if exists uploads_admin_update on storage.objects;
create policy uploads_admin_update on storage.objects for update to authenticated
using (bucket_id = 'uploads' and public.is_admin())
with check (bucket_id = 'uploads' and public.is_admin());

drop policy if exists uploads_admin_delete on storage.objects;
create policy uploads_admin_delete on storage.objects for delete to authenticated
using (bucket_id = 'uploads' and public.is_admin());

-- After creating the first user in Supabase Auth, promote it manually:
-- update public.profiles set role = 'admin', "isOwner" = true
-- where identifier = 'owner@example.com';
-- Never put a password in this file or in source control.
