-- Non-destructive Supabase schema migration.
-- Creates missing application objects and adds missing columns without deleting store data.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  identifier text not null unique,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  "isOwner" boolean not null default false,
  "displayName" text,
  "pictureUrl" text,
  "createdAt" timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin' and "isOwner" = true); $$;

create or replace function public.prevent_profile_privilege_escalation()
returns trigger language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  if (new.role is distinct from old.role or new."isOwner" is distinct from old."isOwner")
     and auth.uid() is not null
     and not public.is_owner() then
    raise exception 'لا يمكن تغيير صلاحيات الحساب';
  end if;
  return new;
end;
$$;

drop trigger if exists prevent_profile_privilege_escalation on public.profiles;
create trigger prevent_profile_privilege_escalation
before update on public.profiles
for each row execute function public.prevent_profile_privilege_escalation();

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;
revoke all on function public.is_owner() from public;
grant execute on function public.is_owner() to anon, authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  user_identifier text := lower(btrim(coalesce(new.email, new.phone, new.id::text)));
  invite_found boolean;
begin
  select exists (select 1 from public.admin_invites where identifier = user_identifier) into invite_found;

  insert into public.profiles as existing_profile (id, identifier, role, "isOwner", "displayName", "pictureUrl")
  values (
    new.id,
    user_identifier,
    case when invite_found then 'admin' else 'customer' end,
    false,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  ) on conflict (id) do update
    set role = case when invite_found then 'admin' else existing_profile.role end;

  if invite_found then
    delete from public.admin_invites where identifier = user_identifier;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  product_code text default ('PRD-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10))),
  description text not null,
  price numeric(12,2) not null,
  "imageUrl" text,
  category text,
  "inStock" boolean not null default true,
  "availabilityMode" text not null default 'ready',
  "costPrice" numeric(12,2) default 0,
  "discountPercentage" numeric(5,2) default 0,
  "discountType" text not null default 'percentage',
  "discountValue" numeric(12,2) not null default 0,
  "productImages" jsonb default '[]'::jsonb,
  variants jsonb default '[]'::jsonb,
  "stockQuantity" integer default 10,
  featured boolean not null default false,
  "isNew" boolean not null default false
);

alter table public.products add column if not exists "discountType" text not null default 'percentage';
alter table public.products add column if not exists "discountValue" numeric(12,2) not null default 0;
alter table public.products add column if not exists "availabilityMode" text not null default 'ready';
update public.products set "discountValue" = "discountPercentage" where "discountType" = 'percentage' and "discountValue" = 0 and "discountPercentage" > 0;
update public.products set "availabilityMode" = case when coalesce("stockQuantity", 0) <= 0 then 'unavailable' when coalesce("inStock", true) then 'ready' else 'preorder' end where "availabilityMode" = 'ready' and (coalesce("stockQuantity", 0) <= 0 or not coalesce("inStock", true));

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'productCode'
  ) then
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'products' and column_name = 'product_code'
    ) then
      alter table public.products rename column "productCode" to product_code;
    else
      update public.products set product_code = coalesce(product_code, "productCode") where product_code is null;
    end if;
  end if;
end;
$$;

alter table public.products add column if not exists product_code text;
alter table public.products alter column product_code set default ('PRD-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10)));
alter table public.products add column if not exists variants jsonb default '[]'::jsonb;
drop index if exists public.products_product_code_unique;
create unique index products_product_code_unique on public.products (product_code) where product_code is not null;

create table if not exists public.discounts (
  id bigint generated by default as identity primary key,
  code text unique not null,
  type text not null,
  value numeric(12,2) not null,
  active boolean not null default true,
  "expiresAt" timestamptz,
  "maxUses" integer,
  "usageCount" integer not null default 0,
  "restrictedUserId" uuid references public.profiles(id) on delete cascade,
  "productIds" jsonb not null default '[]'::jsonb,
  "canCombine" boolean not null default true
);

alter table public.discounts add column if not exists "expiresAt" timestamptz;
alter table public.discounts add column if not exists "maxUses" integer;
alter table public.discounts add column if not exists "usageCount" integer not null default 0;
alter table public.discounts add column if not exists "restrictedUserId" uuid references public.profiles(id) on delete cascade;
alter table public.discounts add column if not exists "productIds" jsonb not null default '[]'::jsonb;
alter table public.discounts add column if not exists "canCombine" boolean not null default true;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'discounts_percentage_limit') then
    alter table public.discounts add constraint discounts_percentage_limit
      check (type <> 'percentage' or (value >= 0 and value <= 100)) not valid;
  end if;
end;
$$;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  items jsonb not null,
  "customerName" text not null,
  province text not null,
  address text not null,
  "nearestLandmark" text not null,
  "phoneNumber" text not null,
  subtotal numeric(12,2) not null,
  "discountCode" text,
  "discountAmount" numeric(12,2) not null,
  "deliveryFee" numeric(12,2) not null,
  "taxAmount" numeric(12,2) not null default 0,
  "finalTotal" numeric(12,2) not null,
  "accountId" uuid references public.profiles(id) on delete set null,
  "accountOrderNumber" integer,
  "requestKey" text,
  status text not null default 'new',
  "isRead" boolean not null default false,
  "createdAt" timestamptz not null default now()
);

alter table public.orders add column if not exists "requestKey" text;
alter table public.orders add column if not exists "taxAmount" numeric(12,2) not null default 0;
alter table public.orders alter column status set default 'new';
create or replace function public.prevent_late_order_cancellation()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if (to_jsonb(new) - 'status' - 'isRead') is distinct from (to_jsonb(old) - 'status' - 'isRead') then
    raise exception 'لا يمكن تعديل الطلب بعد تأكيده';
  end if;
  if new.status is distinct from old.status and not (
    (old.status = 'new' and new.status in ('processing', 'cancelled'))
    or (old.status = 'processing' and new.status = 'delivered')
  ) then
    raise exception 'تغيير حالة الطلب غير مسموح';
  end if;
  return new;
end;
$$;
drop trigger if exists orders_prevent_late_cancellation on public.orders;
create trigger orders_prevent_late_cancellation
before update on public.orders
for each row execute function public.prevent_late_order_cancellation();

create or replace function public.audit_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor_id uuid;
begin
  if new.status is distinct from old.status then
    v_actor_id := coalesce(
      auth.uid(),
      nullif(current_setting('app.order_actor_id', true), '')::uuid
    );
    insert into public.order_status_audit (order_id, previous_status, new_status, changed_by)
    values (new.id, old.status, new.status, v_actor_id);
  end if;
  return new;
end;
$$;
drop trigger if exists orders_status_audit on public.orders;
create trigger orders_status_audit
after update of status on public.orders
for each row execute function public.audit_order_status_change();
create unique index if not exists orders_account_request_key_idx
  on public.orders ("accountId", "requestKey")
  where "accountId" is not null and "requestKey" is not null;

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  "storeName" text,
  tagline text,
  "logoUrl" text,
  "heroTitle" text,
  "heroDescription" text,
  "heroImageUrl" text,
  "heroButtonText" text,
  "featuredSectionTitle" text,
  "featuredProductIds" jsonb,
  "storeCategories" jsonb,
  "deliveryFee" numeric(12,2) not null default 5000,
  "taxRate" numeric(5,2) not null default 0,
  "maintenanceMode" boolean default false,
  "instagramUrl" text,
  "tiktokUrl" text,
  "facebookUrl" text,
  "whatsappUrl" text,
  "aboutTitle" text,
  "aboutText" text
);

alter table public.site_settings add column if not exists "policyTitle" text;
alter table public.site_settings add column if not exists "policyText" text;
alter table public.site_settings add column if not exists "featuredSectionTitle" text;
alter table public.site_settings add column if not exists "featuredProductIds" jsonb;
alter table public.site_settings add column if not exists "storeCategories" jsonb;
alter table public.site_settings add column if not exists "deliveryFee" numeric(12,2) not null default 5000;
alter table public.site_settings add column if not exists "taxRate" numeric(5,2) not null default 0;
alter table public.site_settings alter column "deliveryFee" set default 5000;
alter table public.site_settings add column if not exists "taglineFont" text not null default 'cairo';
alter table public.site_settings add column if not exists "taglineColor" text not null default '#1B1813';

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('home', 'product')),
  "productId" bigint references public.products(id) on delete set null,
  "createdAt" timestamptz not null default now()
);
create index if not exists page_views_product_id_idx on public.page_views ("productId");

create table if not exists public.admin_invites (
  identifier text primary key,
  "createdAt" timestamptz not null default now()
);

update public.profiles as profile
set role = 'admin'
from public.admin_invites as invite
where lower(profile.identifier) = lower(invite.identifier)
  and profile.role <> 'admin';

delete from public.admin_invites as invite
using public.profiles as profile
where lower(profile.identifier) = lower(invite.identifier)
  and profile.role = 'admin';

create table if not exists public.account_carts (
  "accountId" uuid primary key references public.profiles(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.account_coupons (
  "accountId" uuid not null references public.profiles(id) on delete cascade,
  "discountId" bigint not null references public.discounts(id) on delete cascade,
  "savedAt" timestamptz not null default now(),
  primary key ("accountId", "discountId")
);

create index if not exists products_listing_idx on public.products (featured desc, "isNew" desc, id desc);
create index if not exists orders_account_idx on public.orders ("accountId", "createdAt" desc);
create index if not exists orders_created_idx on public.orders ("createdAt" desc);
create index if not exists page_views_type_idx on public.page_views (type);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.discounts enable row level security;
alter table public.orders enable row level security;
alter table public.site_settings enable row level security;
alter table public.page_views enable row level security;
alter table public.admin_invites enable row level security;
alter table public.account_carts enable row level security;
alter table public.account_coupons enable row level security;

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update_own_or_owner on public.profiles;
create policy profiles_update_own_or_owner on public.profiles for update to authenticated
using (id = auth.uid() or public.is_owner()) with check (id = auth.uid() or public.is_owner());

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select to anon, authenticated using (true);
revoke select on public.products from anon, authenticated;
grant select (category) on public.products to authenticated;
drop policy if exists products_admin_write on public.products;
create policy products_admin_write on public.products for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists discounts_public_active_read on public.discounts;
revoke select on public.discounts from anon, authenticated;

drop policy if exists discounts_admin_all on public.discounts;
create policy discounts_admin_all on public.discounts for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists orders_select_own_or_admin on public.orders;
create policy orders_select_own_or_admin on public.orders for select to authenticated
using ("accountId" = auth.uid() or public.is_admin());
revoke select on public.orders from anon, authenticated;
drop policy if exists orders_insert_own_or_admin on public.orders;
revoke insert on public.orders from anon, authenticated;

drop policy if exists orders_update_admin on public.orders;
create policy orders_update_admin on public.orders for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists orders_delete_admin on public.orders;
revoke delete on public.orders from anon, authenticated;

create table if not exists public.order_status_audit (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  previous_status text not null,
  new_status text not null,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now()
);
alter table public.order_status_audit enable row level security;
drop policy if exists order_status_audit_admin_read on public.order_status_audit;
create policy order_status_audit_admin_read on public.order_status_audit for select to authenticated
using (public.is_admin());
revoke insert, update, delete on public.order_status_audit from anon, authenticated;

drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings for select to anon, authenticated using (true);

drop policy if exists site_settings_owner_write on public.site_settings;
create policy site_settings_owner_write on public.site_settings for all to authenticated
using (public.is_owner()) with check (public.is_owner());

drop policy if exists page_views_public_insert on public.page_views;
create policy page_views_public_insert on public.page_views for insert to anon, authenticated with check (true);

drop policy if exists page_views_admin_read on public.page_views;
create policy page_views_admin_read on public.page_views for select to authenticated using (public.is_admin());

drop policy if exists invites_owner_all on public.admin_invites;
create policy invites_owner_all on public.admin_invites for all to authenticated
using (public.is_owner()) with check (public.is_owner());

drop policy if exists carts_own_all on public.account_carts;
create policy carts_own_all on public.account_carts for all to authenticated
using ("accountId" = auth.uid()) with check ("accountId" = auth.uid());

drop policy if exists coupons_own_read on public.account_coupons;
create policy coupons_own_read on public.account_coupons for select to authenticated using ("accountId" = auth.uid());

drop policy if exists coupons_own_insert on public.account_coupons;
create policy coupons_own_insert on public.account_coupons for insert to authenticated with check ("accountId" = auth.uid());

drop policy if exists coupons_own_delete on public.account_coupons;
create policy coupons_own_delete on public.account_coupons for delete to authenticated using ("accountId" = auth.uid());

insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do update set public = true;

drop policy if exists uploads_public_read on storage.objects;
create policy uploads_public_read on storage.objects for select to anon, authenticated
using (bucket_id = 'uploads');

drop policy if exists uploads_admin_insert on storage.objects;
create policy uploads_admin_insert on storage.objects for insert to authenticated
with check (bucket_id = 'uploads' and public.is_admin());

drop policy if exists uploads_admin_update on storage.objects;
create policy uploads_admin_update on storage.objects for update to authenticated
using (bucket_id = 'uploads' and public.is_admin())
with check (bucket_id = 'uploads' and public.is_admin());

drop policy if exists uploads_admin_delete on storage.objects;
create policy uploads_admin_delete on storage.objects for delete to authenticated
using (bucket_id = 'uploads' and public.is_admin());

-- After creating the first user in Supabase Auth, promote it manually:
-- update public.profiles set role = 'admin', "isOwner" = true
-- where identifier = 'owner@example.com';
-- Never put a password in this file or in source control.

create or replace function public.create_order_with_stock(p_account_id uuid, p_payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_account_id uuid := auth.uid();
  v_entry record;
  v_product public.products%rowtype;
  v_discount public.discounts%rowtype;
  v_variant jsonb;
  v_choice jsonb;
  v_selected_variants jsonb;
  v_saved_variants jsonb;
  v_order_items jsonb := '[]'::jsonb;
  v_request_key text;
  v_selected_label text;
  v_selected_key text;
  v_product_id bigint;
  v_quantity integer;
  v_choice_price numeric;
  v_base_price numeric;
  v_unit_price numeric;
  v_subtotal numeric := 0;
  v_discount_amount numeric := 0;
  v_delivery_fee numeric;
  v_tax_rate numeric := 0;
  v_tax_amount numeric := 0;
  v_final_total numeric;
  v_discount_code text;
  v_mode text;
  v_remaining integer;
  v_order_number integer;
  v_maintenance_mode boolean;
  v_entered_discount_code text;
  v_product_discounted boolean := false;
begin
  if p_account_id is null
     or (coalesce(auth.role(), '') <> 'service_role'
         and (v_account_id is null or v_account_id <> p_account_id)) then
    raise exception 'يجب تسجيل الدخول لإرسال الطلب';
  end if;

  v_request_key := nullif(btrim(p_payload->>'requestId'), '');
  if v_request_key is null or length(v_request_key) > 100 then
    raise exception 'تعذر التحقق من رقم الطلب. أعد المحاولة';
  end if;
  if jsonb_typeof(p_payload->'items') is distinct from 'array'
     or jsonb_array_length(coalesce(p_payload->'items', '[]'::jsonb)) = 0 then
    raise exception 'السلة فارغة';
  end if;
  if jsonb_array_length(p_payload->'items') > 50 then
    raise exception 'عدد المنتجات في الطلب تجاوز الحد المسموح';
  end if;

  v_entered_discount_code := upper(btrim(coalesce(p_payload->>'enteredDiscountCode', p_payload->>'discountCode', '')));
  v_discount_code := upper(btrim(coalesce(p_payload->>'discountCode', '')));
  if v_entered_discount_code <> '' and v_entered_discount_code <> v_discount_code then
    raise exception 'طبّق كود الخصم أو امسحه قبل إكمال الطلب';
  end if;
  if coalesce(p_payload->>'finalTotal', '') !~ '^[0-9]+([.][0-9]{1,2})?$' then
    raise exception 'المجموع المرسل غير صحيح. حدّث السلة ثم أعد المحاولة';
  end if;

  perform 1 from public.profiles where id = p_account_id for update;
  if not found then
    raise exception 'تعذر العثور على الحساب';
  end if;

  select "accountOrderNumber" into v_order_number
  from public.orders
  where "accountId" = p_account_id and "requestKey" = v_request_key;
  if found then
    return v_order_number;
  end if;

  select coalesce("maintenanceMode", false) into v_maintenance_mode
  from public.site_settings order by id desc limit 1;
  if coalesce(v_maintenance_mode, false) then
    raise exception 'الطلبات متوقفة مؤقتاً بسبب الصيانة';
  end if;

  if nullif(btrim(p_payload->>'customerName'), '') is null
     or nullif(btrim(p_payload->>'province'), '') is null
     or nullif(btrim(p_payload->>'address'), '') is null
     or nullif(btrim(p_payload->>'nearestLandmark'), '') is null
     or coalesce(p_payload->>'phoneNumber', '') !~ '^07[0-9]{9}$' then
    raise exception 'يرجى إكمال بيانات الطلب وإدخال رقم هاتف عراقي صحيح';
  end if;

  select coalesce(max("accountOrderNumber"), 0) + 1 into v_order_number
  from public.orders where "accountId" = p_account_id;

  for v_entry in
    select value, ordinality
    from jsonb_array_elements(p_payload->'items') with ordinality
    order by ordinality
  loop
    if coalesce(v_entry.value->>'productId', '') !~ '^[0-9]{1,18}$'
       or coalesce(v_entry.value->>'quantity', '') !~ '^[1-9][0-9]{0,2}$'
       or (v_entry.value->>'quantity')::numeric > 100 then
      raise exception 'كمية المنتج غير صحيحة';
    end if;
    v_product_id := (v_entry.value->>'productId')::bigint;
    v_quantity := (v_entry.value->>'quantity')::integer;

    select * into v_product from public.products where id = v_product_id for update;
    if not found then
      raise exception 'أحد المنتجات لم يعد متوفراً';
    end if;
    if v_product.price is null or v_product.price <= 0 then
      raise exception 'سعر أحد المنتجات غير صالح';
    end if;

    v_mode := coalesce(
      v_product."availabilityMode",
      case when coalesce(v_product."stockQuantity", 0) <= 0 then 'unavailable'
           when coalesce(v_product."inStock", true) then 'ready'
           else 'preorder' end
    );
    if v_mode = 'unavailable' or (v_mode = 'ready' and coalesce(v_product."stockQuantity", 0) <= 0) then
      raise exception '% غير متوفر حالياً', v_product.name;
    end if;
    if v_mode = 'ready' then
      v_remaining := coalesce(v_product."stockQuantity", 0) - v_quantity;
      if v_remaining < 0 then
        raise exception 'الكمية المطلوبة من % أكبر من المتوفر', v_product.name;
      end if;
      update public.products
      set "stockQuantity" = v_remaining,
          "inStock" = v_remaining > 0,
          "availabilityMode" = case when v_remaining = 0 then 'unavailable' else 'ready' end
      where id = v_product_id;
    end if;

    v_selected_variants := coalesce(v_entry.value->'selectedVariants', '{}'::jsonb);
    if jsonb_typeof(v_selected_variants) <> 'object' then
      raise exception 'خيارات أحد المنتجات غير صحيحة';
    end if;
    v_saved_variants := '{}'::jsonb;
    v_base_price := v_product.price;

    for v_variant in select value from jsonb_array_elements(coalesce(v_product.variants, '[]'::jsonb))
    loop
      v_selected_label := v_selected_variants->>btrim(v_variant->>'name');
      if v_selected_label is null then
        raise exception 'اختر قيمة % للمنتج %', v_variant->>'name', v_product.name;
      end if;

      select value into v_choice
      from jsonb_array_elements(coalesce(v_variant->'values', '[]'::jsonb))
      where case
        when jsonb_typeof(value) = 'object' then coalesce(value->>'label', value->>'value', '')
        else value #>> '{}'
      end = v_selected_label
      limit 1;
      if not found then
        raise exception 'أحد خيارات المنتج لم يعد متاحاً';
      end if;
      if nullif(v_choice->>'price', '') is not null and (v_choice->>'price')::numeric < 0 then
        raise exception 'سعر خيار المنتج غير صالح';
      end if;
      v_choice_price := coalesce(nullif(v_choice->>'price', '')::numeric, 0);

      if v_choice_price > 0 then
        v_base_price := v_choice_price;
      end if;
      v_saved_variants := v_saved_variants || jsonb_build_object(btrim(v_variant->>'name'), v_selected_label);
    end loop;

    for v_selected_key in select jsonb_object_keys(v_selected_variants)
    loop
      if not exists (
        select 1 from jsonb_array_elements(coalesce(v_product.variants, '[]'::jsonb)) as saved_variant(value)
        where btrim(saved_variant.value->>'name') = v_selected_key
      ) then
        raise exception 'أحد خيارات المنتج غير صالح';
      end if;
    end loop;

    if v_product."discountType" = 'amount' then
      v_base_price := greatest(0, v_base_price - greatest(0, coalesce(v_product."discountValue", 0)));
      v_product_discounted := v_product_discounted or coalesce(v_product."discountValue", 0) > 0;
    else
      v_base_price := v_base_price * (1 - least(100, greatest(0, coalesce(v_product."discountValue", v_product."discountPercentage", 0))) / 100);
      v_product_discounted := v_product_discounted or coalesce(v_product."discountValue", v_product."discountPercentage", 0) > 0;
    end if;
    v_unit_price := round(v_base_price, 2);
    if v_unit_price <= 0 then
      raise exception 'السعر النهائي لأحد المنتجات غير صالح';
    end if;
    v_subtotal := v_subtotal + v_unit_price * v_quantity;
    v_order_items := v_order_items || jsonb_build_array(jsonb_build_object(
      'productId', v_product.id,
      'name', v_product.name,
      'price', v_unit_price,
      'quantity', v_quantity,
      'selectedVariants', v_saved_variants,
      'costPrice', coalesce(v_product."costPrice", 0),
      'discountPercentage', coalesce(v_product."discountPercentage", 0),
      'discountType', coalesce(v_product."discountType", 'percentage'),
      'discountValue', coalesce(v_product."discountValue", v_product."discountPercentage", 0)
    ));
  end loop;

  if v_discount_code <> '' then
    select * into v_discount from public.discounts
    where upper(code) = v_discount_code
    for update;
    if not found then
      raise exception 'كود الخصم غير صالح أو غير فعال';
    end if;
    if not v_discount.active then
      raise exception 'كود الخصم غير صالح أو غير فعال';
    end if;
    if v_discount."expiresAt" is not null and v_discount."expiresAt" <= now() then
      raise exception 'انتهت صلاحية كود الخصم';
    end if;
    if v_discount."maxUses" is not null and v_discount."usageCount" >= v_discount."maxUses" then
      raise exception 'تم استنفاد مرات استخدام كود الخصم';
    end if;
    if v_discount."restrictedUserId" is not null and v_discount."restrictedUserId" <> p_account_id then
      raise exception 'كود الخصم غير متاح لهذا الحساب';
    end if;
    if jsonb_array_length(coalesce(v_discount."productIds", '[]'::jsonb)) > 0
       and exists (
         select 1 from jsonb_array_elements(p_payload->'items') as requested(item)
         where not coalesce(v_discount."productIds" @> jsonb_build_array((requested.item->>'productId')::bigint), false)
       ) then
      raise exception 'كود الخصم غير متاح لأحد المنتجات في السلة';
    end if;
    if not v_discount."canCombine" and v_product_discounted then
      raise exception 'لا يمكن جمع كود الخصم مع خصم المنتج';
    end if;
    if v_discount.value < 0
       or (v_discount.type = 'percentage' and v_discount.value > 100)
       or v_discount.type not in ('percentage', 'fixed') then
      raise exception 'قيمة كود الخصم غير صحيحة';
    end if;
    v_discount_amount := case
      when v_discount.type = 'percentage' then round(v_subtotal * v_discount.value / 100, 2)
      else least(v_subtotal, v_discount.value)
    end;
    update public.discounts
    set "usageCount" = "usageCount" + 1
    where id = v_discount.id;
  end if;

  select greatest(0, coalesce(settings."deliveryFee", 5000)),
         greatest(0, least(100, coalesce(settings."taxRate", 0)))
  into v_delivery_fee, v_tax_rate
  from (select "deliveryFee", "taxRate" from public.site_settings order by id desc limit 1) as settings;
  if not found then
    v_delivery_fee := 5000;
    v_tax_rate := 0;
  end if;
  v_tax_amount := round((v_subtotal - v_discount_amount) * v_tax_rate / 100, 2);
  v_final_total := v_subtotal - v_discount_amount + v_tax_amount + v_delivery_fee;
  if v_final_total < 0 then
    raise exception 'لا يمكن أن يكون المجموع النهائي أقل من صفر';
  end if;
  if round((p_payload->>'finalTotal')::numeric, 2) <> round(v_final_total, 2) then
    raise exception 'المجموع تغير منذ عرض السلة. حدّث السلة ثم أعد إرسال الطلب';
  end if;

  insert into public.orders (
    items, "customerName", province, address, "nearestLandmark", "phoneNumber",
    subtotal, "discountCode", "discountAmount", "deliveryFee", "taxAmount", "finalTotal",
    "accountId", "accountOrderNumber", "requestKey", status, "createdAt"
  ) values (
    v_order_items, btrim(p_payload->>'customerName'), btrim(p_payload->>'province'),
    btrim(p_payload->>'address'), btrim(p_payload->>'nearestLandmark'),
    p_payload->>'phoneNumber', v_subtotal, v_discount_code, v_discount_amount,
    v_delivery_fee, v_tax_amount, v_final_total, p_account_id, v_order_number, v_request_key, 'new', now()
  );
  return v_order_number;
end;
$$;

revoke all on function public.create_order_with_stock(uuid, jsonb) from public;
revoke all on function public.create_order_with_stock(uuid, jsonb) from anon;
grant execute on function public.create_order_with_stock(uuid, jsonb) to authenticated;
grant execute on function public.create_order_with_stock(uuid, jsonb) to service_role;

create or replace function public.update_order_status(p_order_id bigint, p_status text, p_actor_id uuid default null)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor_id uuid;
begin
  if coalesce(auth.role(), '') = 'service_role' then
    v_actor_id := p_actor_id;
  else
    v_actor_id := auth.uid();
    if p_actor_id is not null and p_actor_id <> v_actor_id then
      raise exception 'غير مصرح';
    end if;
  end if;
  if v_actor_id is null or not exists (
    select 1 from public.profiles where id = v_actor_id and role = 'admin'
  ) then
    raise exception 'غير مصرح';
  end if;

  perform set_config('app.order_actor_id', v_actor_id::text, true);
  update public.orders set status = p_status where id = p_order_id;
  if not found then
    raise exception 'الطلب غير موجود';
  end if;
end;
$$;
revoke all on function public.update_order_status(bigint, text, uuid) from public;
grant execute on function public.update_order_status(bigint, text, uuid) to authenticated, service_role;

create or replace function public.cancel_order_if_new(p_order_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_account_id uuid := auth.uid();
begin
  if v_account_id is null then
    raise exception 'يجب تسجيل الدخول لإلغاء الطلب';
  end if;

  update public.orders
  set status = 'cancelled'
  where id = p_order_id
    and "accountId" = v_account_id
    and status = 'new';
  return found;
end;
$$;

revoke all on function public.cancel_order_if_new(bigint) from public;
revoke all on function public.cancel_order_if_new(bigint) from anon;
grant execute on function public.cancel_order_if_new(bigint) to authenticated;

create or replace function public.reset_store(p_owner_id uuid default null)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor_id uuid := auth.uid();
begin
  if coalesce(auth.role(), '') = 'service_role' then
    if p_owner_id is null or not exists (
      select 1 from public.profiles
      where id = p_owner_id and role = 'admin' and "isOwner" = true
    ) then
      raise exception 'فقط مالك المتجر يستطيع إعادة ضبطه';
    end if;
  elsif v_actor_id is null
     or (p_owner_id is not null and p_owner_id <> v_actor_id)
     or not public.is_owner() then
    raise exception 'فقط مالك المتجر يستطيع إعادة ضبطه';
  end if;

  perform 1 from public.profiles order by id for update;

  delete from public.account_coupons;
  delete from public.account_carts;
  delete from public.orders;
  delete from public.products;
  delete from public.discounts;
  delete from public.page_views;
  delete from public.admin_invites;
  delete from public.site_settings;

  insert into public.site_settings (
    "storeName", tagline, "logoUrl", "heroTitle", "heroDescription", "heroImageUrl", "heroButtonText",
    "featuredSectionTitle", "featuredProductIds", "storeCategories", "maintenanceMode",
    "instagramUrl", "tiktokUrl", "facebookUrl", "whatsappUrl", "aboutTitle", "aboutText", "policyTitle", "policyText"
  ) values ('', '', '', '', '', '', '', '', null, '[]'::jsonb, false, '', '', '', '', '', '', '', '');
end;
$$;

revoke all on function public.reset_store(uuid) from public;
revoke all on function public.reset_store(uuid) from anon;
revoke all on function public.reset_store(uuid) from authenticated;
grant execute on function public.reset_store(uuid) to service_role;

create table if not exists public.store_security (
  id smallint primary key check (id = 1),
  pin_hash text not null,
  pin_salt text not null,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  locked_until timestamptz,
  reset_token_hash text,
  reset_token_expires_at timestamptz
);

alter table public.store_security enable row level security;
revoke all on table public.store_security from public, anon, authenticated;
grant select, insert, update on table public.store_security to service_role;

create or replace function public.record_reset_pin_attempt(p_success boolean)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_security public.store_security%rowtype;
begin
  if coalesce(auth.role(), '') <> 'service_role'
     and (auth.uid() is null or not public.is_owner()) then
    raise exception 'غير مصرح';
  end if;

  select * into v_security from public.store_security where id = 1 for update;
  if not found then
    raise exception 'لم يتم إنشاء رمز الأمان';
  end if;

  if v_security.locked_until is not null and v_security.locked_until > now() then
    return jsonb_build_object('ok', false, 'lockedUntil', v_security.locked_until);
  end if;

  if p_success then
    update public.store_security
    set failed_attempts = 0, locked_until = null
    where id = 1;
    return jsonb_build_object('ok', true, 'failedAttempts', 0);
  end if;

  if v_security.locked_until is not null then
    v_security.failed_attempts := 0;
  end if;
  v_security.failed_attempts := v_security.failed_attempts + 1;
  if v_security.failed_attempts >= 5 then
    v_security.locked_until := now() + interval '15 minutes';
  else
    v_security.locked_until := null;
  end if;
  update public.store_security
  set failed_attempts = v_security.failed_attempts, locked_until = v_security.locked_until
  where id = 1;

  return jsonb_build_object(
    'ok', v_security.failed_attempts < 5,
    'failedAttempts', v_security.failed_attempts,
    'lockedUntil', v_security.locked_until
  );
end;
$$;

create or replace function public.consume_store_reset_token(p_token_hash text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_security public.store_security%rowtype;
begin
  if coalesce(auth.role(), '') <> 'service_role'
     and (auth.uid() is null or not public.is_owner()) then
    raise exception 'غير مصرح';
  end if;

  select * into v_security from public.store_security where id = 1 for update;
  if not found
     or v_security.reset_token_hash is distinct from p_token_hash
     or v_security.reset_token_expires_at is null
     or v_security.reset_token_expires_at <= now() then
    return false;
  end if;

  update public.store_security
  set reset_token_hash = null, reset_token_expires_at = null
  where id = 1;
  return true;
end;
$$;

revoke all on function public.record_reset_pin_attempt(boolean) from public, anon, authenticated;
grant execute on function public.record_reset_pin_attempt(boolean) to service_role;
revoke all on function public.consume_store_reset_token(text) from public, anon, authenticated;
grant execute on function public.consume_store_reset_token(text) to service_role;

create or replace function public.complete_store_setup(
  p_owner_id uuid,
  p_settings jsonb,
  p_product jsonb default null,
  p_admin_id uuid default null,
  p_admin_name text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_settings_id bigint;
begin
  if coalesce(auth.role(), '') = 'service_role' then
    if not exists (
      select 1 from public.profiles
      where id = p_owner_id and role = 'admin' and "isOwner" = true
    ) then
      raise exception 'فقط مالك المتجر يستطيع إنشاء المتجر';
    end if;
  elsif auth.uid() is null
     or auth.uid() <> p_owner_id
     or not public.is_owner() then
    raise exception 'فقط مالك المتجر يستطيع إنشاء المتجر';
  end if;

  perform 1 from public.site_settings for update;
  if exists (
    select 1 from public.site_settings
    where length(btrim(coalesce("storeName", ''))) > 0
       or length(btrim(coalesce(tagline, ''))) > 0
  ) or exists (select 1 from public.products) then
    raise exception 'المتجر مُعد مسبقاً';
  end if;

  if p_settings is null
     or length(btrim(coalesce(p_settings ->> 'storeName', ''))) = 0
     or length(btrim(coalesce(p_settings ->> 'tagline', ''))) = 0
     or length(btrim(coalesce(p_settings ->> 'aboutText', ''))) = 0
     or length(btrim(coalesce(p_settings ->> 'policyText', ''))) = 0
     or coalesce(p_settings ->> 'taglineFont', '') not in ('cairo', 'sans', 'serif')
     or coalesce(p_settings ->> 'taglineColor', '') !~* '^#[0-9a-f]{6}$' then
    raise exception 'بيانات المتجر غير مكتملة أو غير صالحة';
  end if;

  if p_product is not null and (
    length(btrim(coalesce(p_product ->> 'name', ''))) = 0
    or length(btrim(coalesce(p_product ->> 'description', ''))) = 0
    or coalesce((p_product ->> 'price')::numeric, 0) <= 0
    or coalesce((p_product ->> 'stockQuantity')::integer, -1) < 0
  ) then
    raise exception 'بيانات المنتج الأول غير صالحة';
  end if;

  update public.site_settings
  set "storeName" = btrim(p_settings ->> 'storeName'),
      tagline = btrim(p_settings ->> 'tagline'),
      "taglineFont" = p_settings ->> 'taglineFont',
      "taglineColor" = p_settings ->> 'taglineColor',
      "aboutTitle" = 'من نحن',
      "aboutText" = btrim(p_settings ->> 'aboutText'),
      "policyTitle" = 'سياساتنا',
      "policyText" = btrim(p_settings ->> 'policyText'),
      "maintenanceMode" = false
  where id = (select id from public.site_settings order by id desc limit 1)
  returning id into v_settings_id;

  if v_settings_id is null then
    insert into public.site_settings (
      "storeName", tagline, "taglineFont", "taglineColor", "aboutTitle", "aboutText",
      "policyTitle", "policyText", "maintenanceMode"
    ) values (
      btrim(p_settings ->> 'storeName'), btrim(p_settings ->> 'tagline'),
      p_settings ->> 'taglineFont', p_settings ->> 'taglineColor',
      'من نحن', btrim(p_settings ->> 'aboutText'),
      'سياساتنا', btrim(p_settings ->> 'policyText'), false
    );
  end if;

  if p_admin_id is not null then
    update public.profiles
    set role = 'admin', "isOwner" = false, "displayName" = btrim(p_admin_name)
    where id = p_admin_id and "isOwner" = false;
    if not found then
      raise exception 'تعذر إعداد حساب المشرف الجديد';
    end if;
  end if;

  if p_product is not null then
    insert into public.products (
      name, description, price, "imageUrl", "productImages", "stockQuantity",
      "inStock", "availabilityMode", featured, "isNew"
    ) values (
      btrim(p_product ->> 'name'),
      btrim(p_product ->> 'description'),
      (p_product ->> 'price')::numeric,
      nullif(p_product ->> 'imageUrl', ''),
      case when nullif(p_product ->> 'imageUrl', '') is null
        then '[]'::jsonb else jsonb_build_array(p_product ->> 'imageUrl') end,
      (p_product ->> 'stockQuantity')::integer,
      coalesce((p_product ->> 'stockQuantity')::integer, 0) > 0,
      case when coalesce((p_product ->> 'stockQuantity')::integer, 0) > 0
        then 'ready' else 'unavailable' end,
      true,
      true
    );
  end if;
end;
$$;

revoke all on function public.complete_store_setup(uuid, jsonb, jsonb, uuid, text) from public, anon, authenticated;
grant execute on function public.complete_store_setup(uuid, jsonb, jsonb, uuid, text) to service_role;

notify pgrst, 'reload schema';
