-- Consolidated, non-destructive Supabase schema repair for the Nasaq app.
-- Run once (and safely rerun) from Supabase Dashboard > SQL Editor.
-- This script never drops application tables or rows.

begin;

create extension if not exists pgcrypto;

-- Profiles mirror Supabase Auth users and store app roles/profile fields.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  identifier text not null unique,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  "isOwner" boolean not null default false,
  "displayName" text,
  "pictureUrl" text,
  "createdAt" timestamptz not null default now()
);

alter table public.profiles add column if not exists id uuid;
alter table public.profiles add column if not exists identifier text;
alter table public.profiles add column if not exists role text not null default 'customer';
alter table public.profiles add column if not exists "isOwner" boolean not null default false;
alter table public.profiles add column if not exists "displayName" text;
alter table public.profiles add column if not exists "pictureUrl" text;
alter table public.profiles add column if not exists "createdAt" timestamptz not null default now();

-- Catalog rows. product_code is the Postgres column; the React/API model uses productCode.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  product_code text,
  description text not null default '',
  price numeric(12,2) not null default 0,
  "imageUrl" text not null default '',
  category text not null default '',
  "inStock" boolean not null default true,
  "availabilityMode" text not null default 'ready',
  "costPrice" numeric(12,2) not null default 0,
  "discountPercentage" numeric(5,2) not null default 0,
  "discountType" text not null default 'percentage',
  "discountValue" numeric(12,2) not null default 0,
  "productImages" jsonb not null default '[]'::jsonb,
  variants jsonb not null default '[]'::jsonb,
  "stockQuantity" integer not null default 10,
  featured boolean not null default false,
  "isNew" boolean not null default false
);

-- Migrate the earlier quoted camel-case column without discarding product codes.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'productCode'
  ) then
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'products' and column_name = 'product_code'
    ) then
      alter table public.products rename column "productCode" to product_code;
    else
      update public.products set product_code = coalesce(product_code, "productCode") where product_code is null;
    end if;
  end if;
end;
$$;

alter table public.products add column if not exists id bigint generated by default as identity;
alter table public.products add column if not exists name text not null default '';
alter table public.products add column if not exists product_code text;
alter table public.products add column if not exists description text not null default '';
alter table public.products add column if not exists price numeric(12,2) not null default 0;
alter table public.products add column if not exists "imageUrl" text not null default '';
alter table public.products add column if not exists category text not null default '';
alter table public.products alter column category set default '';
alter table public.products add column if not exists "inStock" boolean not null default true;
alter table public.products add column if not exists "availabilityMode" text not null default 'ready';
alter table public.products add column if not exists "costPrice" numeric(12,2) not null default 0;
alter table public.products add column if not exists "discountPercentage" numeric(5,2) not null default 0;
alter table public.products add column if not exists "discountType" text not null default 'percentage';
alter table public.products add column if not exists "discountValue" numeric(12,2) not null default 0;
update public.products set "discountValue" = "discountPercentage" where "discountType" = 'percentage' and "discountValue" = 0 and "discountPercentage" > 0;
alter table public.products add column if not exists "productImages" jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists variants jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists "stockQuantity" integer not null default 10;
update public.products set "availabilityMode" = case when coalesce("stockQuantity", 0) <= 0 then 'unavailable' when coalesce("inStock", true) then 'ready' else 'preorder' end where "availabilityMode" = 'ready' and (coalesce("stockQuantity", 0) <= 0 or not coalesce("inStock", true));
alter table public.products add column if not exists featured boolean not null default false;
alter table public.products add column if not exists "isNew" boolean not null default false;

create table if not exists public.discounts (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null,
  value numeric(12,2) not null,
  active boolean not null default true
);

alter table public.discounts add column if not exists id bigint generated by default as identity;
alter table public.discounts add column if not exists code text;
alter table public.discounts add column if not exists type text not null default 'percentage';
alter table public.discounts add column if not exists value numeric(12,2) not null default 0;
alter table public.discounts add column if not exists active boolean not null default true;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  items jsonb not null default '[]'::jsonb,
  "customerName" text not null,
  province text not null,
  address text not null,
  "nearestLandmark" text not null,
  "phoneNumber" text not null,
  subtotal numeric(12,2) not null default 0,
  "discountCode" text not null default '',
  "discountAmount" numeric(12,2) not null default 0,
  "deliveryFee" numeric(12,2) not null default 0,
  "finalTotal" numeric(12,2) not null default 0,
  "accountId" uuid,
  "accountOrderNumber" integer,
  status text not null default 'new',
  "isRead" boolean not null default false,
  "createdAt" timestamptz not null default now()
);

alter table public.orders add column if not exists id bigint generated by default as identity;
alter table public.orders add column if not exists items jsonb not null default '[]'::jsonb;
alter table public.orders add column if not exists "customerName" text not null default '';
alter table public.orders add column if not exists province text not null default '';
alter table public.orders add column if not exists address text not null default '';
alter table public.orders add column if not exists "nearestLandmark" text not null default '';
alter table public.orders add column if not exists "phoneNumber" text not null default '';
alter table public.orders add column if not exists subtotal numeric(12,2) not null default 0;
alter table public.orders add column if not exists "discountCode" text not null default '';
alter table public.orders add column if not exists "discountAmount" numeric(12,2) not null default 0;
alter table public.orders add column if not exists "deliveryFee" numeric(12,2) not null default 0;
alter table public.orders add column if not exists "finalTotal" numeric(12,2) not null default 0;
alter table public.orders add column if not exists "accountId" uuid;
alter table public.orders add column if not exists "accountOrderNumber" integer;
alter table public.orders add column if not exists status text not null default 'new';
alter table public.orders add column if not exists "isRead" boolean not null default false;
alter table public.orders add column if not exists "createdAt" timestamptz not null default now();

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  "storeName" text not null default '',
  tagline text not null default '',
  "logoUrl" text not null default '',
  "heroTitle" text not null default '',
  "heroDescription" text not null default '',
  "heroImageUrl" text not null default '',
  "heroButtonText" text not null default '',
  "featuredSectionTitle" text not null default '',
  "featuredProductIds" jsonb,
  "storeCategories" jsonb not null default '[]'::jsonb,
  "maintenanceMode" boolean not null default false,
  "instagramUrl" text not null default '',
  "tiktokUrl" text not null default '',
  "facebookUrl" text not null default '',
  "whatsappUrl" text not null default '',
  "aboutTitle" text not null default '',
  "aboutText" text not null default '',
  "policyTitle" text not null default '',
  "policyText" text not null default ''
);

alter table public.site_settings add column if not exists id bigint generated by default as identity;
alter table public.site_settings add column if not exists "storeName" text not null default '';
alter table public.site_settings add column if not exists tagline text not null default '';
alter table public.site_settings add column if not exists "logoUrl" text not null default '';
alter table public.site_settings add column if not exists "heroTitle" text not null default '';
alter table public.site_settings add column if not exists "heroDescription" text not null default '';
alter table public.site_settings add column if not exists "heroImageUrl" text not null default '';
alter table public.site_settings add column if not exists "heroButtonText" text not null default '';
alter table public.site_settings add column if not exists "featuredSectionTitle" text not null default '';
alter table public.site_settings add column if not exists "featuredProductIds" jsonb;
alter table public.site_settings add column if not exists "storeCategories" jsonb not null default '[]'::jsonb;
alter table public.site_settings add column if not exists "maintenanceMode" boolean not null default false;
alter table public.site_settings add column if not exists "instagramUrl" text not null default '';
alter table public.site_settings add column if not exists "tiktokUrl" text not null default '';
alter table public.site_settings add column if not exists "facebookUrl" text not null default '';
alter table public.site_settings add column if not exists "whatsappUrl" text not null default '';
alter table public.site_settings add column if not exists "aboutTitle" text not null default '';
alter table public.site_settings add column if not exists "aboutText" text not null default '';
alter table public.site_settings add column if not exists "policyTitle" text not null default '';
alter table public.site_settings add column if not exists "policyText" text not null default '';

alter table public.site_settings alter column "storeName" set default '';
alter table public.site_settings alter column tagline set default '';
alter table public.site_settings alter column "heroTitle" set default '';
alter table public.site_settings alter column "heroDescription" set default '';
alter table public.site_settings alter column "heroButtonText" set default '';
alter table public.site_settings alter column "featuredSectionTitle" set default '';
alter table public.site_settings alter column "aboutTitle" set default '';
alter table public.site_settings alter column "policyTitle" set default '';
alter table public.site_settings alter column "policyText" set default '';

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('home', 'product')),
  "createdAt" timestamptz not null default now()
);

alter table public.page_views add column if not exists id bigint generated by default as identity;
alter table public.page_views add column if not exists type text not null default 'home';
alter table public.page_views add column if not exists "createdAt" timestamptz not null default now();

create table if not exists public.admin_invites (
  identifier text primary key,
  "createdAt" timestamptz not null default now()
);

alter table public.admin_invites add column if not exists identifier text;
alter table public.admin_invites add column if not exists "createdAt" timestamptz not null default now();

create table if not exists public.account_carts (
  "accountId" uuid primary key references public.profiles(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  "updatedAt" timestamptz not null default now()
);

alter table public.account_carts add column if not exists "accountId" uuid;
alter table public.account_carts add column if not exists items jsonb not null default '[]'::jsonb;
alter table public.account_carts add column if not exists "updatedAt" timestamptz not null default now();

create table if not exists public.account_coupons (
  "accountId" uuid not null references public.profiles(id) on delete cascade,
  "discountId" bigint not null references public.discounts(id) on delete cascade,
  "savedAt" timestamptz not null default now(),
  primary key ("accountId", "discountId")
);

alter table public.account_coupons add column if not exists "accountId" uuid;
alter table public.account_coupons add column if not exists "discountId" bigint;
alter table public.account_coupons add column if not exists "savedAt" timestamptz not null default now();

-- Add primary keys to pre-existing partial tables when their rows permit it.
do $$
begin
  if not exists (select 1 from pg_constraint where conrelid = 'public.products'::regclass and contype = 'p')
    and not exists (select 1 from public.products where id is null)
    and not exists (select id from public.products group by id having count(*) > 1) then
    alter table public.products add constraint products_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.discounts'::regclass and contype = 'p')
    and not exists (select 1 from public.discounts where id is null)
    and not exists (select id from public.discounts group by id having count(*) > 1) then
    alter table public.discounts add constraint discounts_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.orders'::regclass and contype = 'p')
    and not exists (select 1 from public.orders where id is null)
    and not exists (select id from public.orders group by id having count(*) > 1) then
    alter table public.orders add constraint orders_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.site_settings'::regclass and contype = 'p')
    and not exists (select 1 from public.site_settings where id is null)
    and not exists (select id from public.site_settings group by id having count(*) > 1) then
    alter table public.site_settings add constraint site_settings_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.page_views'::regclass and contype = 'p')
    and not exists (select 1 from public.page_views where id is null)
    and not exists (select id from public.page_views group by id having count(*) > 1) then
    alter table public.page_views add constraint page_views_pkey primary key (id);
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.admin_invites'::regclass and contype = 'p')
    and not exists (select 1 from public.admin_invites where identifier is null)
    and not exists (select identifier from public.admin_invites group by identifier having count(*) > 1) then
    alter table public.admin_invites add constraint admin_invites_pkey primary key (identifier);
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.account_carts'::regclass and contype = 'p')
    and not exists (select 1 from public.account_carts where "accountId" is null)
    and not exists (select "accountId" from public.account_carts group by "accountId" having count(*) > 1) then
    alter table public.account_carts add constraint account_carts_pkey primary key ("accountId");
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.account_coupons'::regclass and contype = 'p')
    and not exists (select 1 from public.account_coupons where "accountId" is null or "discountId" is null)
    and not exists (select "accountId", "discountId" from public.account_coupons group by "accountId", "discountId" having count(*) > 1) then
    alter table public.account_coupons add constraint account_coupons_pkey primary key ("accountId", "discountId");
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.profiles'::regclass and contype = 'p')
    and not exists (select 1 from public.profiles where id is null)
    and not exists (select id from public.profiles group by id having count(*) > 1) then
    alter table public.profiles add constraint profiles_pkey primary key (id);
  end if;
end;
$$;

-- Enforce lookup keys used by upsert and login flows without changing existing rows.
-- Recreate this named index so it cannot remain attached to the legacy productCode column.
drop index if exists public.products_product_code_unique;
do $$
begin
  if not exists (select 1 from public.profiles where identifier is not null group by identifier having count(*) > 1) then
    create unique index if not exists profiles_identifier_unique on public.profiles (identifier);
  end if;
  if not exists (select 1 from public.discounts where code is not null group by code having count(*) > 1) then
    create unique index if not exists discounts_code_unique on public.discounts (code);
  end if;
  if not exists (select 1 from public.admin_invites where identifier is not null group by identifier having count(*) > 1) then
    create unique index if not exists admin_invites_identifier_unique on public.admin_invites (identifier);
  end if;
  if not exists (select 1 from public.products where product_code is not null and btrim(product_code) <> '' group by product_code having count(*) > 1) then
    create unique index if not exists products_product_code_unique on public.products (product_code) where product_code is not null and btrim(product_code) <> '';
  end if;
end;
$$;

-- Foreign keys, added NOT VALID so legacy orphaned rows do not block the repair;
-- PostgreSQL still enforces each constraint for new writes.
do $$
begin
  if not exists (select 1 from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_auth_user_fkey') then
    alter table public.profiles add constraint profiles_auth_user_fkey foreign key (id) references auth.users(id) on delete cascade not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.orders'::regclass and conname = 'orders_account_id_fkey') then
    alter table public.orders add constraint orders_account_id_fkey foreign key ("accountId") references public.profiles(id) on delete set null not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.account_carts'::regclass and conname = 'account_carts_account_id_fkey') then
    alter table public.account_carts add constraint account_carts_account_id_fkey foreign key ("accountId") references public.profiles(id) on delete cascade not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.account_coupons'::regclass and conname = 'account_coupons_account_id_fkey') then
    alter table public.account_coupons add constraint account_coupons_account_id_fkey foreign key ("accountId") references public.profiles(id) on delete cascade not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.account_coupons'::regclass and conname = 'account_coupons_discount_id_fkey') then
    alter table public.account_coupons add constraint account_coupons_discount_id_fkey foreign key ("discountId") references public.discounts(id) on delete cascade not valid;
  end if;
end;
$$;

create index if not exists products_listing_idx on public.products (featured desc, "isNew" desc, id desc);
create index if not exists orders_account_idx on public.orders ("accountId", "createdAt" desc);
create index if not exists orders_created_idx on public.orders ("createdAt" desc);
create index if not exists page_views_type_idx on public.page_views (type);

-- Auth profile bootstrap used by the app's account/profile queries.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin' and "isOwner" = true); $$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;
revoke all on function public.is_owner() from public;
grant execute on function public.is_owner() to anon, authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  user_identifier text := lower(btrim(coalesce(new.email, new.phone, new.id::text)));
  invite_found boolean;
begin
  select exists (select 1 from public.admin_invites where identifier = user_identifier) into invite_found;

  insert into public.profiles as existing_profile (id, identifier, role, "isOwner", "displayName", "pictureUrl")
  values (
    new.id,
    user_identifier,
    case when invite_found then 'admin' else 'customer' end,
    false,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  ) on conflict (id) do update
    set role = case when invite_found then 'admin' else existing_profile.role end;

  if invite_found then
    delete from public.admin_invites where identifier = user_identifier;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

update public.profiles as profile
set role = 'admin'
from public.admin_invites as invite
where lower(profile.identifier) = lower(invite.identifier)
  and profile.role <> 'admin';

delete from public.admin_invites as invite
using public.profiles as profile
where lower(profile.identifier) = lower(invite.identifier)
  and profile.role = 'admin';

-- RLS policies are recreated by name so this file can be safely rerun.
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.discounts enable row level security;
alter table public.orders enable row level security;
alter table public.site_settings enable row level security;
alter table public.page_views enable row level security;
alter table public.admin_invites enable row level security;
alter table public.account_carts enable row level security;
alter table public.account_coupons enable row level security;

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());
drop policy if exists profiles_update_own_or_owner on public.profiles;
create policy profiles_update_own_or_owner on public.profiles for update to authenticated
using (id = auth.uid() or public.is_owner()) with check (id = auth.uid() or public.is_owner());

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select to anon, authenticated using (true);
drop policy if exists products_admin_write on public.products;
create policy products_admin_write on public.products for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists discounts_public_active_read on public.discounts;
create policy discounts_public_active_read on public.discounts for select to anon, authenticated using (active = true);
drop policy if exists discounts_admin_all on public.discounts;
create policy discounts_admin_all on public.discounts for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists orders_select_own_or_admin on public.orders;
create policy orders_select_own_or_admin on public.orders for select to authenticated
using ("accountId" = auth.uid() or public.is_admin());
drop policy if exists orders_insert_own_or_admin on public.orders;
create policy orders_insert_own_or_admin on public.orders for insert to authenticated
with check ("accountId" = auth.uid() or public.is_admin());
drop policy if exists orders_update_admin on public.orders;
create policy orders_update_admin on public.orders for update to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists orders_delete_admin on public.orders;
create policy orders_delete_admin on public.orders for delete to authenticated using (public.is_admin());

drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings for select to anon, authenticated using (true);
drop policy if exists site_settings_owner_write on public.site_settings;
create policy site_settings_owner_write on public.site_settings for all to authenticated
using (public.is_owner()) with check (public.is_owner());

drop policy if exists page_views_public_insert on public.page_views;
create policy page_views_public_insert on public.page_views for insert to anon, authenticated with check (true);
drop policy if exists page_views_admin_read on public.page_views;
create policy page_views_admin_read on public.page_views for select to authenticated using (public.is_admin());

drop policy if exists invites_owner_all on public.admin_invites;
create policy invites_owner_all on public.admin_invites for all to authenticated
using (public.is_owner()) with check (public.is_owner());

drop policy if exists carts_own_all on public.account_carts;
create policy carts_own_all on public.account_carts for all to authenticated
using ("accountId" = auth.uid()) with check ("accountId" = auth.uid());

drop policy if exists coupons_own_read on public.account_coupons;
create policy coupons_own_read on public.account_coupons for select to authenticated using ("accountId" = auth.uid());
drop policy if exists coupons_own_insert on public.account_coupons;
create policy coupons_own_insert on public.account_coupons for insert to authenticated with check ("accountId" = auth.uid());
drop policy if exists coupons_own_delete on public.account_coupons;
create policy coupons_own_delete on public.account_coupons for delete to authenticated using ("accountId" = auth.uid());

-- Supabase Storage bucket and policies used for product/category/store images.
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do update set public = true;

drop policy if exists uploads_public_read on storage.objects;
create policy uploads_public_read on storage.objects for select to anon, authenticated using (bucket_id = 'uploads');
drop policy if exists uploads_admin_insert on storage.objects;
create policy uploads_admin_insert on storage.objects for insert to authenticated
with check (bucket_id = 'uploads' and public.is_admin());
drop policy if exists uploads_admin_update on storage.objects;
create policy uploads_admin_update on storage.objects for update to authenticated
using (bucket_id = 'uploads' and public.is_admin()) with check (bucket_id = 'uploads' and public.is_admin());
drop policy if exists uploads_admin_delete on storage.objects;
create policy uploads_admin_delete on storage.objects for delete to authenticated
using (bucket_id = 'uploads' and public.is_admin());

commit;
notify pgrst, 'reload schema';
